/**
 * Comprehensive mock data for local development & testing.
 * Covers: users, dogs, posts, events, businesses, adoptions, lost reports,
 * match results, map pins, and calendar entries.
 *
 * Images: seed-based picsum.photos (consistent, no API key required).
 * Location: Central London parks & neighbourhoods.
 */

import type {
  UserProfile,
  DogProfile,
  Post,
  DogEvent,
  Business,
  AdoptionDog,
  LostReport,
  CalendarEntry,
  MapPin,
} from '../types';
import type { MatchResult } from './api/matching';
import type { FeedPage } from './api/feed';

// ── Helpers ──────────────────────────────────────────────────────────────────

const NOW = new Date().toISOString();

/** Offset from today by `days` (negative = past, positive = future). */
function d(days: number, hour = 10, minute = 0): string {
  const dt = new Date();
  dt.setDate(dt.getDate() + days);
  dt.setHours(hour, minute, 0, 0);
  return dt.toISOString();
}

function img(seed: string, w = 400, h = 400) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

const REACTIONS_ZERO = { woof: 0, heart: 0, paw: 0, laugh: 0, wow: 0 };

// ── Users ─────────────────────────────────────────────────────────────────────

export const MOCK_USERS: UserProfile[] = [
  {
    uid: 'user_sarah',
    email: 'sarah.chen@example.com',
    displayName: 'Sarah Chen',
    photoURL: img('sarah_avatar', 200, 200),
    city: 'London',
    neighbourhood: 'Hampstead',
    subscriptionTier: 'premium',
    subscriptionExpiry: d(180),
    stripeCustomerId: 'cus_mock_sarah',
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-120),
    updatedAt: NOW,
  },
  {
    uid: 'user_james',
    email: 'james.mitchell@example.com',
    displayName: 'James Mitchell',
    photoURL: img('james_avatar', 200, 200),
    city: 'London',
    neighbourhood: 'Camden',
    subscriptionTier: 'free',
    subscriptionExpiry: null,
    stripeCustomerId: null,
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: false, allowPawRequests: true, allowMessages: 'friends', showInFeed: true },
    createdAt: d(-90),
    updatedAt: NOW,
  },
  {
    uid: 'user_emma',
    email: 'emma.rodriguez@example.com',
    displayName: 'Emma Rodriguez',
    photoURL: img('emma_avatar', 200, 200),
    city: 'London',
    neighbourhood: 'Notting Hill',
    subscriptionTier: 'premium',
    subscriptionExpiry: d(90),
    stripeCustomerId: 'cus_mock_emma',
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-60),
    updatedAt: NOW,
  },
  {
    uid: 'user_liam',
    email: 'liam.thompson@example.com',
    displayName: 'Liam Thompson',
    photoURL: img('liam_avatar', 200, 200),
    city: 'London',
    neighbourhood: 'Shoreditch',
    subscriptionTier: 'free',
    subscriptionExpiry: null,
    stripeCustomerId: null,
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-45),
    updatedAt: NOW,
  },
  {
    uid: 'user_olivia',
    email: 'olivia.patel@example.com',
    displayName: 'Olivia Patel',
    photoURL: img('olivia_avatar', 200, 200),
    city: 'London',
    neighbourhood: 'Clapham',
    subscriptionTier: 'premium',
    subscriptionExpiry: d(270),
    stripeCustomerId: 'cus_mock_olivia',
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-30),
    updatedAt: NOW,
  },
  {
    uid: 'user_shelter',
    email: 'adopt@happypawsrescue.org',
    displayName: 'Happy Paws Rescue',
    photoURL: img('shelter_avatar', 200, 200),
    city: 'London',
    neighbourhood: 'Battersea',
    subscriptionTier: 'free',
    subscriptionExpiry: null,
    stripeCustomerId: null,
    pushToken: null,
    privacySettings: { showOnMap: false, showLastSeen: false, allowPawRequests: false, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-200),
    updatedAt: NOW,
  },
];

// ── Dogs ──────────────────────────────────────────────────────────────────────

export const MOCK_DOGS: DogProfile[] = [
  {
    id: 'dog_max',
    ownerUid: 'user_sarah',
    name: 'Max',
    breed: 'Golden Retriever',
    gender: 'male',
    dateOfBirth: '2021-03-15',
    weightKg: 32,
    size: 'large',
    photoURLs: [img('max_dog1'), img('max_dog2'), img('max_dog3')],
    bio: 'Sunshine in dog form 🌟 Max loves everyone he meets and has never met a puddle he didn\'t want to investigate.',
    traits: ['Playful', 'Affectionate', 'Loyal', 'Gentle Soul'],
    badges: ['Park King', 'Social Butterfly', 'Early Adopter'],
    energyLevel: 'high',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'playful',
    moodUpdatedAt: d(-1),
    isActive: true,
    createdAt: d(-120),
    updatedAt: NOW,
  },
  {
    id: 'dog_luna',
    ownerUid: 'user_james',
    name: 'Luna',
    breed: 'Border Collie',
    gender: 'female',
    dateOfBirth: '2020-07-22',
    weightKg: 21,
    size: 'medium',
    photoURLs: [img('luna_dog1'), img('luna_dog2')],
    bio: 'Luna is a certified genius. She\'ll outsmart you at frisbee and then demand belly rubs as a victory lap.',
    traits: ['Smart Cookie', 'Playful', 'Loyal', 'Energetic'],
    badges: ['Kilometer King', 'Pawtner in Crime'],
    energyLevel: 'high',
    dogSocialPref: 'okay',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-90),
    updatedAt: NOW,
  },
  {
    id: 'dog_cooper',
    ownerUid: 'user_emma',
    name: 'Cooper',
    breed: 'Labrador Retriever',
    gender: 'male',
    dateOfBirth: '2022-01-10',
    weightKg: 28,
    size: 'large',
    photoURLs: [img('cooper_dog1'), img('cooper_dog2')],
    bio: 'Cooper believes every person is a potential friend and every bin is a potential snack opportunity.',
    traits: ['Foodie', 'Affectionate', 'Clumsy but Cute', 'Playful'],
    badges: ['Beach Pup', 'Social Butterfly'],
    energyLevel: 'medium',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-60),
    updatedAt: NOW,
  },
  {
    id: 'dog_bella',
    ownerUid: 'user_liam',
    name: 'Bella',
    breed: 'French Bulldog',
    gender: 'female',
    dateOfBirth: '2021-11-05',
    weightKg: 11,
    size: 'small',
    photoURLs: [img('bella_dog1'), img('bella_dog2')],
    bio: 'Bella is a professional napper with a part-time job snoring. She will consider playing with you after her 3rd nap.',
    traits: ['Drama Queen', 'Lazy Bum', 'Foodie', 'Velcro Dog'],
    badges: ['Latte Lad', 'Early Adopter'],
    energyLevel: 'low',
    dogSocialPref: 'okay',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'calm',
    moodUpdatedAt: d(-2),
    isActive: true,
    createdAt: d(-45),
    updatedAt: NOW,
  },
  {
    id: 'dog_charlie',
    ownerUid: 'user_olivia',
    name: 'Charlie',
    breed: 'Cockapoo',
    gender: 'male',
    dateOfBirth: '2022-06-18',
    weightKg: 9,
    size: 'small',
    photoURLs: [img('charlie_dog1'), img('charlie_dog2'), img('charlie_dog3')],
    bio: 'Charlie has an infectious zest for life. Warning: extended Charlie exposure may cause spontaneous smiling.',
    traits: ['Playful', 'Affectionate', 'Cheeky', 'Cuddly'],
    badges: ['Social Butterfly', 'Neighborhood Star'],
    energyLevel: 'high',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'playful',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-30),
    updatedAt: NOW,
  },
  {
    id: 'dog_daisy',
    ownerUid: 'user_james',
    name: 'Daisy',
    breed: 'Dachshund',
    gender: 'female',
    dateOfBirth: '2020-04-12',
    weightKg: 7,
    size: 'tiny',
    photoURLs: [img('daisy_dog1')],
    bio: 'Short legs, long ambitions. Daisy is convinced she\'s the biggest dog at the park and will argue the point.',
    traits: ['Bold', 'Stubborn but Sweet', 'Loyal', 'Adventure Seeker'],
    badges: ['Park King', 'Kilometer King'],
    energyLevel: 'medium',
    dogSocialPref: 'okay',
    humanSocialPref: 'okay',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(-1),
    isActive: true,
    createdAt: d(-90),
    updatedAt: NOW,
  },
  {
    id: 'dog_rosie',
    ownerUid: 'user_sarah',
    name: 'Rosie',
    breed: 'Cavalier King Charles Spaniel',
    gender: 'female',
    dateOfBirth: '2023-02-28',
    weightKg: 8,
    size: 'small',
    photoURLs: [img('rosie_dog1'), img('rosie_dog2')],
    bio: 'Rosie is royalty in a fluffy coat. She expects cuddles on demand and treats as a constitutional right.',
    traits: ['Cuddly', 'Gentle Soul', 'Velcro Dog', 'Affectionate'],
    badges: ['Early Adopter'],
    energyLevel: 'low',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'calm',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-30),
    updatedAt: NOW,
  },
  {
    id: 'dog_buddy',
    ownerUid: 'user_emma',
    name: 'Buddy',
    breed: 'Beagle',
    gender: 'male',
    dateOfBirth: '2021-09-03',
    weightKg: 13,
    size: 'medium',
    photoURLs: [img('buddy_dog1'), img('buddy_dog2')],
    bio: 'Buddy follows his nose wherever life takes him. That nose has gotten him into trouble more times than we\'ll admit.',
    traits: ['Foodie', 'Adventure Seeker', 'Stubborn but Sweet', 'Playful'],
    badges: ['Beach Pup', 'Latte Lad'],
    energyLevel: 'medium',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(-1),
    isActive: true,
    createdAt: d(-60),
    updatedAt: NOW,
  },
  {
    id: 'dog_mia',
    ownerUid: 'user_olivia',
    name: 'Mia',
    breed: 'Toy Poodle',
    gender: 'female',
    dateOfBirth: '2022-12-01',
    weightKg: 5,
    size: 'tiny',
    photoURLs: [img('mia_dog1'), img('mia_dog2')],
    bio: 'Mia is proof that great things come in small packages. She can learn a trick in 10 minutes and will remind you about it forever.',
    traits: ['Smart Cookie', 'Sassy', 'Affectionate', 'Show-off'],
    badges: ['Social Butterfly'],
    energyLevel: 'medium',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'playful',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-25),
    updatedAt: NOW,
  },
  {
    id: 'dog_bear',
    ownerUid: 'user_liam',
    name: 'Bear',
    breed: 'Bernese Mountain Dog',
    gender: 'male',
    dateOfBirth: '2020-12-25',
    weightKg: 45,
    size: 'giant',
    photoURLs: [img('bear_dog1'), img('bear_dog2')],
    bio: 'Bear is a gentle giant who thinks he\'s a lapdog. Spoiler: he is not. But we let him believe it.',
    traits: ['Gentle Soul', 'Cuddly', 'Loyal', 'Calm'],
    badges: ['Park King', 'Neighborhood Star'],
    energyLevel: 'low',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'calm',
    moodUpdatedAt: d(-3),
    isActive: true,
    createdAt: d(-50),
    updatedAt: NOW,
  },
];

// ── Adoption Dogs ─────────────────────────────────────────────────────────────

export const MOCK_ADOPTION_DOGS: AdoptionDog[] = [
  {
    id: 'adopt_rex',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Rex',
    breed: 'German Shepherd Mix',
    gender: 'male',
    ageMonths: 24,
    weightKg: 30,
    photoURLs: [img('rex_adopt1'), img('rex_adopt2')],
    bio: 'Rex was found wandering Battersea. He\'s come a long way and is now looking for a forever home with a garden.',
    traits: ['Loyal', 'Smart Cookie', 'Gentle Soul'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'available',
    applicationCount: 3,
    createdAt: d(-30),
  },
  {
    id: 'adopt_pixie',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Pixie',
    breed: 'Chihuahua Mix',
    gender: 'female',
    ageMonths: 14,
    weightKg: 3,
    photoURLs: [img('pixie_adopt1'), img('pixie_adopt2')],
    bio: 'Pixie is small but mighty. She loves cuddles, hates rain, and will steal your heart in under 60 seconds.',
    traits: ['Sassy', 'Cuddly', 'Bold'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'available',
    applicationCount: 7,
    createdAt: d(-14),
  },
  {
    id: 'adopt_honey',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Honey',
    breed: 'Labrador Mix',
    gender: 'female',
    ageMonths: 6,
    weightKg: 12,
    photoURLs: [img('honey_adopt1'), img('honey_adopt2'), img('honey_adopt3')],
    bio: 'Honey is a puppy with boundless love to give. She\'s in foster care and doing brilliantly with children.',
    traits: ['Playful', 'Affectionate', 'Foodie'],
    isNeutered: false,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'available',
    applicationCount: 12,
    createdAt: d(-7),
  },
  {
    id: 'adopt_shadow',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Shadow',
    breed: 'Greyhound',
    gender: 'male',
    ageMonths: 48,
    weightKg: 28,
    photoURLs: [img('shadow_adopt1')],
    bio: 'Retired racing greyhound looking for a quiet sofa and kind humans. Counter-surfer but we\'re working on it.',
    traits: ['Gentle Soul', 'Calm', 'Loyal'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'available',
    applicationCount: 2,
    createdAt: d(-21),
  },
  {
    id: 'adopt_bruno',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Bruno',
    breed: 'Rottweiler',
    gender: 'male',
    ageMonths: 36,
    weightKg: 40,
    photoURLs: [img('bruno_adopt1'), img('bruno_adopt2')],
    bio: 'Bruno is a big softie who needs an experienced owner. He gives the best leaning cuddles in the business.',
    traits: ['Loyal', 'Bold', 'Protective'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'pending',
    applicationCount: 1,
    createdAt: d(-45),
  },
  {
    id: 'adopt_cleo',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Cleo',
    breed: 'Cocker Spaniel Mix',
    gender: 'female',
    ageMonths: 18,
    weightKg: 12,
    photoURLs: [img('cleo_adopt1'), img('cleo_adopt2')],
    bio: 'Cleo was recently adopted into her forever home! She loves long walks in Greenwich Park.',
    traits: ['Affectionate', 'Gentle Soul', 'Adventure Seeker'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'adopted',
    applicationCount: 5,
    createdAt: d(-60),
  },
];

// ── Businesses ────────────────────────────────────────────────────────────────

const STANDARD_HOURS = {
  monday: { open: '09:00', close: '18:00' },
  tuesday: { open: '09:00', close: '18:00' },
  wednesday: { open: '09:00', close: '18:00' },
  thursday: { open: '09:00', close: '18:00' },
  friday: { open: '09:00', close: '18:00' },
  saturday: { open: '10:00', close: '16:00' },
  sunday: null,
};

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'biz_vet_hampstead',
    name: 'Hampstead Paws Veterinary',
    category: 'vet',
    description: 'Award-winning vet practice in the heart of Hampstead. Specialists in small animals, with on-site diagnostics and 24/7 emergency cover.',
    address: '42 Heath Street, Hampstead, London NW3 1EN',
    latitude: 51.5570,
    longitude: -0.1780,
    phone: '+44 20 7435 1100',
    website: 'https://example.com/hampstead-paws-vet',
    photoURLs: [img('vet1_photo1'), img('vet1_photo2')],
    rating: 4.8,
    reviewCount: 234,
    openingHours: { ...STANDARD_HOURS, saturday: { open: '09:00', close: '17:00' }, sunday: { open: '10:00', close: '14:00' } },
    isPremiumPartner: true,
    createdAt: d(-365),
  },
  {
    id: 'biz_groomer_camden',
    name: 'Fluffy & Fresh Grooming',
    category: 'groomer',
    description: 'Boutique dog grooming salon specialising in breed-specific cuts, luxury spa treatments, and anxiety-free grooming for nervous dogs.',
    address: '15 Camden High Street, London NW1 7JE',
    latitude: 51.5390,
    longitude: -0.1426,
    phone: '+44 20 7267 8844',
    website: null,
    photoURLs: [img('groomer1_photo1'), img('groomer1_photo2')],
    rating: 4.6,
    reviewCount: 156,
    openingHours: STANDARD_HOURS,
    isPremiumPartner: false,
    createdAt: d(-200),
  },
  {
    id: 'biz_cafe_shoreditch',
    name: 'The Barkery Dog Café',
    category: 'dog_cafe',
    description: 'London\'s cosiest dog-friendly café. Bring your pup, sip craft coffee, and enjoy dog-safe treats alongside your own. No booking needed for small groups.',
    address: '8 Brick Lane, Shoreditch, London E1 6RF',
    latitude: 51.5220,
    longitude: -0.0720,
    phone: '+44 20 7247 5566',
    website: 'https://example.com/the-barkery',
    photoURLs: [img('cafe1_photo1'), img('cafe1_photo2'), img('cafe1_photo3')],
    rating: 4.9,
    reviewCount: 412,
    openingHours: {
      monday: { open: '08:00', close: '17:00' },
      tuesday: { open: '08:00', close: '17:00' },
      wednesday: { open: '08:00', close: '17:00' },
      thursday: { open: '08:00', close: '20:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    isPremiumPartner: true,
    createdAt: d(-300),
  },
  {
    id: 'biz_petstore_notting',
    name: 'Paws Pet Emporium',
    category: 'pet_store',
    description: 'Premium pet supplies, natural food, supplements, and accessories. We stock over 3,000 products including many UK-exclusive brands.',
    address: '33 Portobello Road, Notting Hill, London W11 1LU',
    latitude: 51.5150,
    longitude: -0.2010,
    phone: '+44 20 7229 3300',
    website: 'https://example.com/paws-emporium',
    photoURLs: [img('petstore1_photo1'), img('petstore1_photo2')],
    rating: 4.4,
    reviewCount: 98,
    openingHours: { ...STANDARD_HOURS, saturday: { open: '09:30', close: '18:00' }, sunday: { open: '11:00', close: '17:00' } },
    isPremiumPartner: false,
    createdAt: d(-150),
  },
  {
    id: 'biz_trainer_clapham',
    name: 'London Canine Academy',
    category: 'trainer',
    description: 'Positive-reinforcement training for puppies through to advanced obedience. Group classes, 1:1 sessions, and reactive dog programmes available.',
    address: '7 Clapham Common Southside, London SW4 7AA',
    latitude: 51.4613,
    longitude: -0.1398,
    phone: '+44 20 8673 9900',
    website: 'https://example.com/london-canine-academy',
    photoURLs: [img('trainer1_photo1')],
    rating: 4.7,
    reviewCount: 87,
    openingHours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '08:00', close: '17:00' },
      sunday: { open: '09:00', close: '14:00' },
    },
    isPremiumPartner: true,
    createdAt: d(-180),
  },
  {
    id: 'biz_boarding_battersea',
    name: 'Battersea Boarding Suites',
    category: 'boarding',
    description: 'Five-star dog boarding with individual suites, webcam access for owners, daily walks in Battersea Park, and gourmet meals. Your dog won\'t want to leave.',
    address: '20 Battersea Park Road, London SW11 4LT',
    latitude: 51.4790,
    longitude: -0.1560,
    phone: '+44 20 7622 1188',
    website: 'https://example.com/battersea-boarding',
    photoURLs: [img('boarding1_photo1'), img('boarding1_photo2')],
    rating: 4.5,
    reviewCount: 63,
    openingHours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '20:00' },
      saturday: { open: '07:00', close: '20:00' },
      sunday: { open: '07:00', close: '20:00' },
    },
    isPremiumPartner: false,
    createdAt: d(-250),
  },
];

// ── Events ────────────────────────────────────────────────────────────────────

export const MOCK_EVENTS: DogEvent[] = [
  {
    id: 'event_hampstead_meetup',
    creatorUid: 'user_sarah',
    title: 'Hampstead Heath Dog Meetup 🐕',
    description: 'Monthly off-lead social for all dogs and their humans. We meet at the Kenwood end near the ponds. Bring poo bags, treats, and good vibes!',
    category: 'meetup',
    latitude: 51.5636,
    longitude: -0.1556,
    locationName: 'Hampstead Heath — Kenwood',
    address: 'Kenwood House, Hampstead Lane, London NW3 7JR',
    startAt: d(3, 10, 0),
    endAt: d(3, 12, 0),
    maxAttendees: 50,
    attendeeCount: 23,
    isRSVPd: false,
    coverImageURL: img('event_hampstead', 800, 400),
    isPremiumOnly: false,
    createdAt: d(-7),
  },
  {
    id: 'event_puppy_training',
    creatorUid: 'user_olivia',
    title: 'Puppy Foundation Class 🎓',
    description: 'Six-week positive reinforcement programme for puppies 8–16 weeks. Socialisation, sit, stay, recall and lead walking covered. Limit 8 puppies per class.',
    category: 'training',
    latitude: 51.4613,
    longitude: -0.1398,
    locationName: 'London Canine Academy',
    address: '7 Clapham Common Southside, London SW4 7AA',
    startAt: d(5, 11, 0),
    endAt: d(5, 12, 0),
    maxAttendees: 8,
    attendeeCount: 6,
    isRSVPd: false,
    coverImageURL: img('event_training', 800, 400),
    isPremiumOnly: false,
    createdAt: d(-14),
  },
  {
    id: 'event_birthday_bash',
    creatorUid: 'user_sarah',
    title: 'Max\'s 3rd Birthday Bash 🎂🎉',
    description: 'Max is turning 3! Come celebrate with us at the park. There will be a pupcake station, doggy ice cream, and a paddling pool. Humans get prosecco (or tea).',
    category: 'birthday',
    latitude: 51.5604,
    longitude: -0.1620,
    locationName: 'Hampstead Heath — Parliament Hill',
    address: 'Parliament Hill, London NW5 1QR',
    startAt: d(7, 14, 0),
    endAt: d(7, 17, 0),
    maxAttendees: 30,
    attendeeCount: 18,
    isRSVPd: true,
    coverImageURL: img('event_birthday', 800, 400),
    isPremiumOnly: false,
    createdAt: d(-10),
  },
  {
    id: 'event_charity_walk',
    creatorUid: 'user_emma',
    title: 'Charity Walkies for Dogs Trust 🎗️',
    description: 'Join us for a 5km sponsored walk through Hyde Park in aid of Dogs Trust. All dogs welcome. Raise £20+ and your dog gets an official finisher bandana!',
    category: 'charity',
    latitude: 51.5074,
    longitude: -0.1657,
    locationName: 'Hyde Park — Diana Memorial Fountain',
    address: 'Hyde Park, London W2 2UH',
    startAt: d(10, 9, 30),
    endAt: d(10, 13, 0),
    maxAttendees: 200,
    attendeeCount: 87,
    isRSVPd: false,
    coverImageURL: img('event_charity', 800, 400),
    isPremiumOnly: false,
    createdAt: d(-20),
  },
];

// ── Lost Reports ──────────────────────────────────────────────────────────────

export const MOCK_LOST_REPORTS: LostReport[] = [
  {
    id: 'lost_biscuit',
    reporterUid: 'user_james',
    dogId: null,
    dogName: 'Biscuit',
    dogBreed: 'Jack Russell Terrier',
    dogPhotoURL: img('biscuit_lost', 400, 400),
    dogDescription: 'Tan and white Jack Russell, male, no collar when lost. Responds to "Biscuit". Has a small scar above left eye.',
    status: 'lost',
    lastSeenLatitude: 51.5237,
    lastSeenLongitude: -0.0770,
    lastSeenAddress: 'Shoreditch High Street near Old Street roundabout',
    lastSeenAt: d(-1, 16, 30),
    rewardOffered: true,
    rewardAmount: 250,
    contactPhone: '+44 7700 900123',
    sightings: [
      {
        id: 'sighting_1',
        reportId: 'lost_biscuit',
        reporterUid: 'user_liam',
        latitude: 51.5240,
        longitude: -0.0780,
        address: 'Curtain Road, Shoreditch',
        note: 'Saw him running east on Curtain Road, looked scared but uninjured.',
        photoURL: null,
        seenAt: d(-1, 18, 15),
        createdAt: d(-1, 18, 20),
      },
    ],
    isBroadcast: true,
    createdAt: d(-1, 16, 45),
    updatedAt: d(-1, 18, 25),
  },
  {
    id: 'lost_cookie',
    reporterUid: 'user_olivia',
    dogId: null,
    dogName: 'Cookie',
    dogBreed: 'Maltese',
    dogPhotoURL: img('cookie_lost', 400, 400),
    dogDescription: 'White Maltese, female, 3 years old. Wearing a pink collar with a bone-shaped tag. Very friendly.',
    status: 'sighted',
    lastSeenLatitude: 51.4613,
    lastSeenLongitude: -0.1378,
    lastSeenAddress: 'Clapham Common, near the bandstand',
    lastSeenAt: d(-2, 11, 0),
    rewardOffered: false,
    rewardAmount: null,
    contactPhone: '+44 7700 900456',
    sightings: [
      {
        id: 'sighting_2',
        reportId: 'lost_cookie',
        reporterUid: 'user_emma',
        latitude: 51.4620,
        longitude: -0.1390,
        address: 'Clapham High Street',
        note: 'Spotted near the Sainsbury\'s entrance, being coaxed by staff. She ran off towards the park.',
        photoURL: img('cookie_sighting', 400, 400),
        seenAt: d(-1, 9, 30),
        createdAt: d(-1, 9, 45),
      },
    ],
    isBroadcast: true,
    createdAt: d(-2, 11, 30),
    updatedAt: d(-1, 9, 50),
  },
  {
    id: 'lost_zeus',
    reporterUid: 'user_sarah',
    dogId: null,
    dogName: 'Zeus',
    dogBreed: 'Husky',
    dogPhotoURL: img('zeus_lost', 400, 400),
    dogDescription: 'Black and white Husky, male, blue eyes. Microchipped. Escaped from garden in Primrose Hill. Very friendly, will approach people.',
    status: 'found',
    lastSeenLatitude: 51.5392,
    lastSeenLongitude: -0.1591,
    lastSeenAddress: 'Fitzroy Road, Primrose Hill',
    lastSeenAt: d(-5, 8, 0),
    rewardOffered: false,
    rewardAmount: null,
    contactPhone: '+44 7700 900789',
    sightings: [],
    isBroadcast: true,
    createdAt: d(-5, 8, 30),
    updatedAt: d(-4, 14, 0),
  },
];

// ── Posts ─────────────────────────────────────────────────────────────────────

export const MOCK_POSTS: Post[] = [
  {
    id: 'post_1',
    authorUid: 'user_sarah',
    authorDogId: 'dog_max',
    type: 'photo',
    text: 'Golden hour at Hampstead Heath never gets old 🌅 Max insisted on posing for at least 47 photos before agreeing one was good enough.',
    mediaURLs: [img('post_max_sunset', 800, 600)],
    reactions: { woof: 42, heart: 28, paw: 15, laugh: 3, wow: 7 },
    myReaction: null,
    commentCount: 12,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-1, 18, 30),
    updatedAt: d(-1, 18, 30),
  },
  {
    id: 'post_2',
    authorUid: 'user_james',
    authorDogId: 'dog_luna',
    type: 'photo',
    text: 'Luna discovered the mud pit at Primrose Hill. She is UNREPENTANT. Bath time is going to be a battle. 💀',
    mediaURLs: [img('post_luna_mud', 800, 600), img('post_luna_mud2', 800, 600)],
    reactions: { woof: 18, heart: 9, paw: 6, laugh: 34, wow: 2 },
    myReaction: null,
    commentCount: 8,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-1, 14, 15),
    updatedAt: d(-1, 14, 15),
  },
  {
    id: 'post_3',
    authorUid: 'user_emma',
    authorDogId: 'dog_cooper',
    type: 'photo',
    text: 'Cooper got his first agility rosette today!! He knocked over 4 jumps, ran through the tunnel backwards, and stole a treat from the judge\'s pocket — but he got there eventually 🏆',
    mediaURLs: [img('post_cooper_agility', 800, 600)],
    reactions: { woof: 65, heart: 43, paw: 29, laugh: 21, wow: 14 },
    myReaction: null,
    commentCount: 22,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-2, 16, 0),
    updatedAt: d(-2, 16, 0),
  },
  {
    id: 'post_4',
    authorUid: 'user_liam',
    authorDogId: 'dog_bella',
    type: 'text',
    text: 'Bella has developed a new hobby: judging everyone at the dog park from a safe distance without participating. She sat on the bench with me for 45 minutes, watched other dogs play, then demanded we go home. She\'s me. I am Bella.',
    mediaURLs: [],
    reactions: { woof: 31, heart: 44, paw: 12, laugh: 89, wow: 5 },
    myReaction: null,
    commentCount: 33,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-2, 20, 30),
    updatedAt: d(-2, 20, 30),
  },
  {
    id: 'post_5',
    authorUid: 'user_olivia',
    authorDogId: 'dog_charlie',
    type: 'event',
    text: '🎉 We\'re hosting a birthday bash for Max on Saturday! Charlie and I will be there with homemade pupcakes. Come celebrate with us at Parliament Hill! 🎂',
    mediaURLs: [img('post_birthday_event', 800, 600)],
    reactions: { woof: 24, heart: 31, paw: 18, laugh: 4, wow: 9 },
    myReaction: null,
    commentCount: 15,
    eventRef: 'event_birthday_bash',
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-3, 10, 0),
    updatedAt: d(-3, 10, 0),
  },
  {
    id: 'post_6',
    authorUid: 'user_emma',
    authorDogId: 'dog_buddy',
    type: 'lost_alert',
    text: '🚨 LOST DOG — Biscuit the Jack Russell was last seen near Old Street yesterday evening. Please share widely! Contact details in the report.',
    mediaURLs: [img('biscuit_lost', 400, 400)],
    reactions: { woof: 5, heart: 3, paw: 2, laugh: 0, wow: 1 },
    myReaction: null,
    commentCount: 4,
    eventRef: null,
    lostReportRef: 'lost_biscuit',
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-1, 19, 0),
    updatedAt: d(-1, 19, 0),
  },
  {
    id: 'post_7',
    authorUid: 'user_shelter',
    authorDogId: 'dog_max',
    type: 'adoption',
    text: '🐶 Meet Honey! This 6-month-old Labrador mix is looking for her forever home. She\'s brilliant with children and other dogs. Applications open now — link in profile.',
    mediaURLs: [img('honey_adopt1'), img('honey_adopt2')],
    reactions: { woof: 78, heart: 102, paw: 55, laugh: 2, wow: 23 },
    myReaction: null,
    commentCount: 41,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: 'adopt_honey',
    isPublic: true,
    createdAt: d(-3, 12, 0),
    updatedAt: d(-3, 12, 0),
  },
  {
    id: 'post_8',
    authorUid: 'user_sarah',
    authorDogId: 'dog_rosie',
    type: 'tip',
    text: '💡 Dog care tip: Did you know Cavaliers are prone to overheating in summer? We keep Rosie\'s walks to early morning and evening during hot spells, and always carry a collapsible water bowl. Sharing in case it helps other spaniel owners! 🌡️',
    mediaURLs: [],
    reactions: { woof: 15, heart: 28, paw: 9, laugh: 1, wow: 6 },
    myReaction: null,
    commentCount: 7,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-4, 9, 0),
    updatedAt: d(-4, 9, 0),
  },
  {
    id: 'post_9',
    authorUid: 'user_james',
    authorDogId: 'dog_daisy',
    type: 'photo',
    text: 'Daisy decided that a squirrel was more important than our recall training session. We\'re going back to basics. Again. 🐿️',
    mediaURLs: [img('post_daisy_squirrel', 800, 600)],
    reactions: { woof: 27, heart: 19, paw: 8, laugh: 56, wow: 3 },
    myReaction: null,
    commentCount: 14,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-5, 11, 30),
    updatedAt: d(-5, 11, 30),
  },
  {
    id: 'post_10',
    authorUid: 'user_olivia',
    authorDogId: 'dog_mia',
    type: 'photo',
    text: 'Mia graduated from her puppy class today! She only bit the instructor once and it was very gentle. We\'re calling it a success 🎓✨',
    mediaURLs: [img('post_mia_graduate', 800, 600), img('post_mia_graduate2', 800, 600)],
    reactions: { woof: 49, heart: 62, paw: 33, laugh: 17, wow: 11 },
    myReaction: null,
    commentCount: 28,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-5, 17, 0),
    updatedAt: d(-5, 17, 0),
  },
  {
    id: 'post_11',
    authorUid: 'user_emma',
    authorDogId: 'dog_cooper',
    type: 'event',
    text: '🎗️ We\'re joining the Dogs Trust charity walk next weekend! Cooper and Buddy are training hard (read: eating extra treats for fuel). Come walk with us and raise money for a brilliant cause!',
    mediaURLs: [img('post_charity_walk', 800, 600)],
    reactions: { woof: 33, heart: 41, paw: 22, laugh: 5, wow: 8 },
    myReaction: null,
    commentCount: 16,
    eventRef: 'event_charity_walk',
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-6, 13, 0),
    updatedAt: d(-6, 13, 0),
  },
  {
    id: 'post_12',
    authorUid: 'user_liam',
    authorDogId: 'dog_bear',
    type: 'tip',
    text: '🐻 PSA from a Bernese Mountain Dog owner: these gentle giants need more exercise than their chill demeanour suggests. Bear does 1.5 hours a day and is a completely different dog (in a good way) compared to when we did 30 minutes. Please do your breed research before adopting!',
    mediaURLs: [],
    reactions: { woof: 88, heart: 112, paw: 67, laugh: 3, wow: 29 },
    myReaction: null,
    commentCount: 45,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-7, 21, 0),
    updatedAt: d(-7, 21, 0),
  },
];

export const MOCK_FEED_PAGE: FeedPage = {
  items: MOCK_POSTS,
  cursor: null,
  hasMore: false,
};

// ── Match Results ─────────────────────────────────────────────────────────────

/** Mock matches for any active dog. Target dogs are all MOCK_DOGS. */
export const MOCK_MATCHES: MatchResult[] = [
  {
    dog: MOCK_DOGS[1], // Luna
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_luna',
      score: 92,
      breakdown: { traits: 90, energy: 95, size: 85, social: 95, distance: 95 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[4], // Charlie
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_charlie',
      score: 87,
      breakdown: { traits: 88, energy: 90, size: 82, social: 92, distance: 80 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[2], // Cooper
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_cooper',
      score: 84,
      breakdown: { traits: 80, energy: 80, size: 90, social: 92, distance: 85 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[7], // Buddy
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_buddy',
      score: 79,
      breakdown: { traits: 75, energy: 75, size: 88, social: 90, distance: 72 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[8], // Mia
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_mia',
      score: 74,
      breakdown: { traits: 78, energy: 70, size: 65, social: 88, distance: 78 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[5], // Daisy
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_daisy',
      score: 69,
      breakdown: { traits: 65, energy: 60, size: 72, social: 80, distance: 90 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[6], // Rosie
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_rosie',
      score: 66,
      breakdown: { traits: 70, energy: 55, size: 68, social: 85, distance: 60 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[9], // Bear
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_bear',
      score: 58,
      breakdown: { traits: 60, energy: 45, size: 50, social: 82, distance: 65 },
      computedAt: d(-1),
    },
  },
];

// ── Map Pins ──────────────────────────────────────────────────────────────────

export const MOCK_MAP_PINS: MapPin[] = [
  // Businesses
  { type: 'business', businessId: 'biz_vet_hampstead', name: 'Hampstead Paws Vet', category: 'vet', latitude: 51.5570, longitude: -0.1780, rating: 4.8 },
  { type: 'business', businessId: 'biz_groomer_camden', name: 'Fluffy & Fresh Grooming', category: 'groomer', latitude: 51.5390, longitude: -0.1426, rating: 4.6 },
  { type: 'business', businessId: 'biz_cafe_shoreditch', name: 'The Barkery Dog Café', category: 'dog_cafe', latitude: 51.5220, longitude: -0.0720, rating: 4.9 },
  { type: 'business', businessId: 'biz_petstore_notting', name: 'Paws Pet Emporium', category: 'pet_store', latitude: 51.5150, longitude: -0.2010, rating: 4.4 },
  { type: 'business', businessId: 'biz_trainer_clapham', name: 'London Canine Academy', category: 'trainer', latitude: 51.4613, longitude: -0.1398, rating: 4.7 },
  { type: 'business', businessId: 'biz_boarding_battersea', name: 'Battersea Boarding Suites', category: 'boarding', latitude: 51.4790, longitude: -0.1560, rating: 4.5 },
  // Lost dogs
  { type: 'lost', reportId: 'lost_biscuit', dogName: 'Biscuit', photoURL: img('biscuit_lost', 400, 400), latitude: 51.5237, longitude: -0.0770, lastSeenAt: d(-1, 16, 30) },
  { type: 'lost', reportId: 'lost_cookie', dogName: 'Cookie', photoURL: img('cookie_lost', 400, 400), latitude: 51.4613, longitude: -0.1378, lastSeenAt: d(-2, 11, 0) },
];

// ── Calendar Entries ──────────────────────────────────────────────────────────

export const MOCK_CALENDAR_ENTRIES: CalendarEntry[] = [
  {
    id: 'cal_vet',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: null,
    title: 'Max — Annual Vet Check',
    notes: 'Booster vaccines due. Bring vaccination record.',
    startAt: d(1, 10, 0),
    endAt: d(1, 10, 45),
    category: 'vet',
    reminderMinutes: 60,
    createdAt: d(-7),
  },
  {
    id: 'cal_playdate',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: null,
    title: 'Playdate with Luna & Daisy',
    notes: 'Meeting at Regent\'s Park off-lead area. Bring the long lead for recall practice.',
    startAt: d(2, 9, 30),
    endAt: d(2, 11, 30),
    category: 'playdate',
    reminderMinutes: 30,
    createdAt: d(-3),
  },
  {
    id: 'cal_training',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: null,
    title: 'Group Training Class',
    notes: 'Advanced recall & distraction work. Remember to bring high-value treats (cheese or chicken).',
    startAt: d(3, 18, 30),
    endAt: d(3, 19, 30),
    category: 'training',
    reminderMinutes: 60,
    createdAt: d(-5),
  },
  {
    id: 'cal_grooming',
    ownerUid: 'user_sarah',
    dogId: 'dog_rosie',
    eventId: null,
    title: 'Rosie — Grooming Appointment',
    notes: 'Full groom + ear cleaning at Fluffy & Fresh. Drop off 10am, collect 1pm.',
    startAt: d(4, 10, 0),
    endAt: d(4, 13, 0),
    category: 'grooming',
    reminderMinutes: 60,
    createdAt: d(-10),
  },
  {
    id: 'cal_birthday',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: 'event_birthday_bash',
    title: 'Max\'s 3rd Birthday Party 🎂',
    notes: 'Parliament Hill. Order pupcakes from The Barkery. Bring spare towels and the paddling pool.',
    startAt: d(7, 14, 0),
    endAt: d(7, 17, 0),
    category: 'birthday',
    reminderMinutes: 120,
    createdAt: d(-10),
  },
  {
    id: 'cal_charity',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: 'event_charity_walk',
    title: 'Dogs Trust Charity Walk 🎗️',
    notes: 'Hyde Park, Diana Memorial. Meet Cooper & Buddy at the gate.',
    startAt: d(10, 9, 30),
    endAt: d(10, 13, 0),
    category: 'charity',
    reminderMinutes: 90,
    createdAt: d(-5),
  },
  {
    id: 'cal_medication',
    ownerUid: 'user_sarah',
    dogId: 'dog_rosie',
    eventId: null,
    title: 'Rosie — Flea & Worm Treatment',
    notes: 'Monthly Advocate spot-on. Wear gloves!',
    startAt: d(14, 8, 0),
    endAt: d(14, 8, 15),
    category: 'medication',
    reminderMinutes: 1440,
    createdAt: d(-2),
  },
  {
    id: 'cal_meetup',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: 'event_hampstead_meetup',
    title: 'Hampstead Heath Monthly Meetup',
    notes: 'Kenwood end. Arrive early to grab a good spot.',
    startAt: d(3, 10, 0),
    endAt: d(3, 12, 0),
    category: 'meetup',
    reminderMinutes: 60,
    createdAt: d(-1),
  },
];
