/**
 * Comprehensive mock data for local development & testing.
 * Covers: users, dogs, posts, events, businesses, adoptions, lost reports,
 * match results, map pins, and calendar entries.
 *
 * Images: seed-based picsum.photos (consistent, no API key required).
 * Location: Central London parks & neighbourhoods.
 */

import type {
  UserProfile,
  DogProfile,
  Post,
  DogEvent,
  Business,
  AdoptionDog,
  LostReport,
  CalendarEntry,
  MapPin,
} from '../types';
import type { MatchResult } from './api/matching';
import type { FeedPage } from './api/feed';

// ── Helpers ──────────────────────────────────────────────────────────────────

const NOW = new Date().toISOString();

/** Offset from today by `days` (negative = past, positive = future). */
function d(days: number, hour = 10, minute = 0): string {
  const dt = new Date();
  dt.setDate(dt.getDate() + days);
  dt.setHours(hour, minute, 0, 0);
  return dt.toISOString();
}

function img(seed: string, w = 400, h = 400) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

/** Dog-specific placeholder image via LoremFlickr (always shows a dog). */
function dogImg(breed: string, lock: number, w = 400, h = 400) {
  return `https://loremflickr.com/${w}/${h}/${encodeURIComponent(breed)},dog?lock=${lock}`;
}

/** Dog-with-owner placeholder — shows a person and their dog together. */
function dogOwnerImg(breed: string, lock: number, w = 200, h = 200) {
  return `https://loremflickr.com/${w}/${h}/${encodeURIComponent(breed)},dog,person?lock=${lock}`;
}

const REACTIONS_ZERO = { woof: 0, heart: 0, paw: 0, laugh: 0, wow: 0 };

// ── Users ─────────────────────────────────────────────────────────────────────

export const MOCK_USERS: UserProfile[] = [
  {
    uid: 'user_sarah',
    email: 'sarah.chen@example.com',
    displayName: 'Sarah Chen',
    photoURL: dogOwnerImg('golden retriever', 201),
    city: 'London',
    neighbourhood: 'Hampstead',
    subscriptionTier: 'premium',
    subscriptionExpiry: d(180),
    stripeCustomerId: 'cus_mock_sarah',
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-120),
    updatedAt: NOW,
  },
  {
    uid: 'user_james',
    email: 'james.mitchell@example.com',
    displayName: 'James Mitchell',
    photoURL: dogOwnerImg('border collie', 202),
    city: 'London',
    neighbourhood: 'Camden',
    subscriptionTier: 'free',
    subscriptionExpiry: null,
    stripeCustomerId: null,
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: false, allowPawRequests: true, allowMessages: 'friends', showInFeed: true },
    createdAt: d(-90),
    updatedAt: NOW,
  },
  {
    uid: 'user_emma',
    email: 'emma.rodriguez@example.com',
    displayName: 'Emma Rodriguez',
    photoURL: dogOwnerImg('labrador retriever', 203),
    city: 'London',
    neighbourhood: 'Notting Hill',
    subscriptionTier: 'premium',
    subscriptionExpiry: d(90),
    stripeCustomerId: 'cus_mock_emma',
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-60),
    updatedAt: NOW,
  },
  {
    uid: 'user_liam',
    email: 'liam.thompson@example.com',
    displayName: 'Liam Thompson',
    photoURL: dogOwnerImg('french bulldog', 204),
    city: 'London',
    neighbourhood: 'Shoreditch',
    subscriptionTier: 'free',
    subscriptionExpiry: null,
    stripeCustomerId: null,
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-45),
    updatedAt: NOW,
  },
  {
    uid: 'user_olivia',
    email: 'olivia.patel@example.com',
    displayName: 'Olivia Patel',
    photoURL: dogOwnerImg('cockapoo', 205),
    city: 'London',
    neighbourhood: 'Clapham',
    subscriptionTier: 'premium',
    subscriptionExpiry: d(270),
    stripeCustomerId: 'cus_mock_olivia',
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-30),
    updatedAt: NOW,
  },
  {
    uid: 'user_shelter',
    email: 'adopt@happypawsrescue.org',
    displayName: 'Happy Paws Rescue',
    photoURL: dogImg('dog', 206, 200, 200),
    city: 'London',
    neighbourhood: 'Battersea',
    subscriptionTier: 'free',
    subscriptionExpiry: null,
    stripeCustomerId: null,
    pushToken: null,
    privacySettings: { showOnMap: false, showLastSeen: false, allowPawRequests: false, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-200),
    updatedAt: NOW,
  },
  {
    uid: 'user_noah',
    email: 'noah.williams@example.com',
    displayName: 'Noah Williams',
    photoURL: dogOwnerImg('australian shepherd', 207),
    city: 'London',
    neighbourhood: 'Islington',
    subscriptionTier: 'free',
    subscriptionExpiry: null,
    stripeCustomerId: null,
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-55),
    updatedAt: NOW,
  },
  {
    uid: 'user_ava',
    email: 'ava.brown@example.com',
    displayName: 'Ava Brown',
    photoURL: dogOwnerImg('miniature schnauzer', 208),
    city: 'London',
    neighbourhood: 'Richmond',
    subscriptionTier: 'premium',
    subscriptionExpiry: d(120),
    stripeCustomerId: 'cus_mock_ava',
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-40),
    updatedAt: NOW,
  },
  {
    uid: 'user_marcus',
    email: 'marcus.johnson@example.com',
    displayName: 'Marcus Johnson',
    photoURL: dogOwnerImg('staffordshire bull terrier', 209),
    city: 'London',
    neighbourhood: 'Greenwich',
    subscriptionTier: 'free',
    subscriptionExpiry: null,
    stripeCustomerId: null,
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: false, allowPawRequests: true, allowMessages: 'friends', showInFeed: true },
    createdAt: d(-70),
    updatedAt: NOW,
  },
  {
    uid: 'user_priya',
    email: 'priya.singh@example.com',
    displayName: 'Priya Singh',
    photoURL: dogOwnerImg('shih tzu', 210),
    city: 'London',
    neighbourhood: 'Fulham',
    subscriptionTier: 'premium',
    subscriptionExpiry: d(200),
    stripeCustomerId: 'cus_mock_priya',
    pushToken: null,
    privacySettings: { showOnMap: true, showLastSeen: true, allowPawRequests: true, allowMessages: 'everyone', showInFeed: true },
    createdAt: d(-20),
    updatedAt: NOW,
  },
];

// ── Dogs ──────────────────────────────────────────────────────────────────────

export const MOCK_DOGS: DogProfile[] = [
  {
    id: 'dog_max',
    ownerUid: 'user_sarah',
    name: 'Max',
    breed: 'Golden Retriever',
    gender: 'male',
    dateOfBirth: '2021-03-15',
    weightKg: 32,
    size: 'large',
    photoURLs: [dogImg('golden retriever', 1), dogImg('golden retriever', 2), dogImg('golden retriever', 3)],
    bio: 'Sunshine in dog form 🌟 Max loves everyone he meets and has never met a puddle he didn\'t want to investigate.',
    traits: ['Playful', 'Affectionate', 'Loyal', 'Gentle Soul'],
    badges: ['Park King', 'Social Butterfly', 'Early Adopter'],
    energyLevel: 'high',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'playful',
    moodUpdatedAt: d(-1),
    isActive: true,
    createdAt: d(-120),
    updatedAt: NOW,
  },
  {
    id: 'dog_luna',
    ownerUid: 'user_james',
    name: 'Luna',
    breed: 'Border Collie',
    gender: 'female',
    dateOfBirth: '2020-07-22',
    weightKg: 21,
    size: 'medium',
    photoURLs: [dogImg('border collie', 10), dogImg('border collie', 11)],
    bio: 'Luna is a certified genius. She\'ll outsmart you at frisbee and then demand belly rubs as a victory lap.',
    traits: ['Smart Cookie', 'Playful', 'Loyal', 'Energetic'],
    badges: ['Kilometer King', 'Pawtner in Crime'],
    energyLevel: 'high',
    dogSocialPref: 'okay',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-90),
    updatedAt: NOW,
  },
  {
    id: 'dog_cooper',
    ownerUid: 'user_emma',
    name: 'Cooper',
    breed: 'Labrador Retriever',
    gender: 'male',
    dateOfBirth: '2022-01-10',
    weightKg: 28,
    size: 'large',
    photoURLs: [dogImg('labrador retriever', 20), dogImg('labrador retriever', 21)],
    bio: 'Cooper believes every person is a potential friend and every bin is a potential snack opportunity.',
    traits: ['Foodie', 'Affectionate', 'Clumsy but Cute', 'Playful'],
    badges: ['Beach Pup', 'Social Butterfly'],
    energyLevel: 'medium',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-60),
    updatedAt: NOW,
  },
  {
    id: 'dog_bella',
    ownerUid: 'user_liam',
    name: 'Bella',
    breed: 'French Bulldog',
    gender: 'female',
    dateOfBirth: '2021-11-05',
    weightKg: 11,
    size: 'small',
    photoURLs: [dogImg('french bulldog', 30), dogImg('french bulldog', 31)],
    bio: 'Bella is a professional napper with a part-time job snoring. She will consider playing with you after her 3rd nap.',
    traits: ['Drama Queen', 'Lazy Bum', 'Foodie', 'Velcro Dog'],
    badges: ['Latte Lad', 'Early Adopter'],
    energyLevel: 'low',
    dogSocialPref: 'okay',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'calm',
    moodUpdatedAt: d(-2),
    isActive: true,
    createdAt: d(-45),
    updatedAt: NOW,
  },
  {
    id: 'dog_charlie',
    ownerUid: 'user_olivia',
    name: 'Charlie',
    breed: 'Cockapoo',
    gender: 'male',
    dateOfBirth: '2022-06-18',
    weightKg: 9,
    size: 'small',
    photoURLs: [dogImg('cockapoo', 40), dogImg('cockapoo', 41), dogImg('cockapoo', 42)],
    bio: 'Charlie has an infectious zest for life. Warning: extended Charlie exposure may cause spontaneous smiling.',
    traits: ['Playful', 'Affectionate', 'Cheeky', 'Cuddly'],
    badges: ['Social Butterfly', 'Neighborhood Star'],
    energyLevel: 'high',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'playful',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-30),
    updatedAt: NOW,
  },
  {
    id: 'dog_daisy',
    ownerUid: 'user_james',
    name: 'Daisy',
    breed: 'Dachshund',
    gender: 'female',
    dateOfBirth: '2020-04-12',
    weightKg: 7,
    size: 'tiny',
    photoURLs: [dogImg('dachshund', 50)],
    bio: 'Short legs, long ambitions. Daisy is convinced she\'s the biggest dog at the park and will argue the point.',
    traits: ['Bold', 'Stubborn but Sweet', 'Loyal', 'Adventure Seeker'],
    badges: ['Park King', 'Kilometer King'],
    energyLevel: 'medium',
    dogSocialPref: 'okay',
    humanSocialPref: 'okay',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(-1),
    isActive: true,
    createdAt: d(-90),
    updatedAt: NOW,
  },
  {
    id: 'dog_rosie',
    ownerUid: 'user_sarah',
    name: 'Rosie',
    breed: 'Cavalier King Charles Spaniel',
    gender: 'female',
    dateOfBirth: '2023-02-28',
    weightKg: 8,
    size: 'small',
    photoURLs: [dogImg('cavalier king charles spaniel', 60), dogImg('cavalier king charles spaniel', 61)],
    bio: 'Rosie is royalty in a fluffy coat. She expects cuddles on demand and treats as a constitutional right.',
    traits: ['Cuddly', 'Gentle Soul', 'Velcro Dog', 'Affectionate'],
    badges: ['Early Adopter'],
    energyLevel: 'low',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'calm',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-30),
    updatedAt: NOW,
  },
  {
    id: 'dog_buddy',
    ownerUid: 'user_emma',
    name: 'Buddy',
    breed: 'Beagle',
    gender: 'male',
    dateOfBirth: '2021-09-03',
    weightKg: 13,
    size: 'medium',
    photoURLs: [dogImg('beagle', 70), dogImg('beagle', 71)],
    bio: 'Buddy follows his nose wherever life takes him. That nose has gotten him into trouble more times than we\'ll admit.',
    traits: ['Foodie', 'Adventure Seeker', 'Stubborn but Sweet', 'Playful'],
    badges: ['Beach Pup', 'Latte Lad'],
    energyLevel: 'medium',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(-1),
    isActive: true,
    createdAt: d(-60),
    updatedAt: NOW,
  },
  {
    id: 'dog_mia',
    ownerUid: 'user_olivia',
    name: 'Mia',
    breed: 'Toy Poodle',
    gender: 'female',
    dateOfBirth: '2022-12-01',
    weightKg: 5,
    size: 'tiny',
    photoURLs: [dogImg('toy poodle', 80), dogImg('toy poodle', 81)],
    bio: 'Mia is proof that great things come in small packages. She can learn a trick in 10 minutes and will remind you about it forever.',
    traits: ['Smart Cookie', 'Sassy', 'Affectionate', 'Show-off'],
    badges: ['Social Butterfly'],
    energyLevel: 'medium',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'playful',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-25),
    updatedAt: NOW,
  },
  {
    id: 'dog_bear',
    ownerUid: 'user_liam',
    name: 'Bear',
    breed: 'Bernese Mountain Dog',
    gender: 'male',
    dateOfBirth: '2020-12-25',
    weightKg: 45,
    size: 'giant',
    photoURLs: [dogImg('bernese mountain dog', 90), dogImg('bernese mountain dog', 91)],
    bio: 'Bear is a gentle giant who thinks he\'s a lapdog. Spoiler: he is not. But we let him believe it.',
    traits: ['Gentle Soul', 'Cuddly', 'Loyal', 'Calm'],
    badges: ['Park King', 'Neighborhood Star'],
    energyLevel: 'low',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'calm',
    moodUpdatedAt: d(-3),
    isActive: true,
    createdAt: d(-50),
    updatedAt: NOW,
  },
  {
    id: 'dog_atlas',
    ownerUid: 'user_noah',
    name: 'Atlas',
    breed: 'Australian Shepherd',
    gender: 'male',
    dateOfBirth: '2021-05-20',
    weightKg: 25,
    size: 'medium',
    photoURLs: [dogImg('australian shepherd', 91), dogImg('australian shepherd', 92), dogImg('australian shepherd', 93)],
    bio: 'Atlas has one blue eye, one brown eye, and the stamina of a triathlete. He\'d hike Snowdonia every weekend if we let him.',
    traits: ['Energetic', 'Smart Cookie', 'Loyal', 'Adventure Seeker'],
    badges: ['Kilometer King', 'Park King'],
    energyLevel: 'high',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'playful',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-55),
    updatedAt: NOW,
  },
  {
    id: 'dog_pepper',
    ownerUid: 'user_ava',
    name: 'Pepper',
    breed: 'Miniature Schnauzer',
    gender: 'female',
    dateOfBirth: '2022-08-14',
    weightKg: 7,
    size: 'small',
    photoURLs: [dogImg('miniature schnauzer', 94), dogImg('miniature schnauzer', 95)],
    bio: 'Pepper is the mayor of every room she walks into. Opinionated, stylish, and absolutely certain the world revolves around her eyebrows.',
    traits: ['Sassy', 'Smart Cookie', 'Bold', 'Affectionate'],
    badges: ['Social Butterfly', 'Early Adopter'],
    energyLevel: 'medium',
    dogSocialPref: 'okay',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(-1),
    isActive: true,
    createdAt: d(-40),
    updatedAt: NOW,
  },
  {
    id: 'dog_rex',
    ownerUid: 'user_marcus',
    name: 'Rex',
    breed: 'Staffordshire Bull Terrier',
    gender: 'male',
    dateOfBirth: '2020-10-08',
    weightKg: 17,
    size: 'medium',
    photoURLs: [dogImg('staffordshire bull terrier', 96), dogImg('staffordshire bull terrier', 97)],
    bio: 'Rex is living proof that Staffies are the biggest soppy babies in the dog world. He cries when the postman leaves without playing.',
    traits: ['Affectionate', 'Playful', 'Gentle Soul', 'Loyal'],
    badges: ['Neighborhood Star', 'Pawtner in Crime'],
    energyLevel: 'high',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'happy',
    moodUpdatedAt: d(-2),
    isActive: true,
    createdAt: d(-70),
    updatedAt: NOW,
  },
  {
    id: 'dog_nala',
    ownerUid: 'user_priya',
    name: 'Nala',
    breed: 'Shih Tzu',
    gender: 'female',
    dateOfBirth: '2023-01-07',
    weightKg: 6,
    size: 'tiny',
    photoURLs: [dogImg('shih tzu', 98), dogImg('shih tzu', 99), dogImg('shih tzu', 100)],
    bio: 'Nala wears hair clips and takes them very seriously. She has a wardrobe larger than mine and she knows it.',
    traits: ['Cuddly', 'Sassy', 'Velcro Dog', 'Cheeky'],
    badges: ['Latte Lad', 'Social Butterfly'],
    energyLevel: 'low',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: false,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'calm',
    moodUpdatedAt: d(0),
    isActive: true,
    createdAt: d(-20),
    updatedAt: NOW,
  },
  {
    id: 'dog_finn',
    ownerUid: 'user_noah',
    name: 'Finn',
    breed: 'Irish Setter',
    gender: 'male',
    dateOfBirth: '2019-06-30',
    weightKg: 30,
    size: 'large',
    photoURLs: [dogImg('irish setter', 101), dogImg('irish setter', 102)],
    bio: 'Finn is a magnificent disaster. His coat is supermodel-level, his recall is non-existent. We love him unconditionally anyway.',
    traits: ['Energetic', 'Playful', 'Bold', 'Show-off'],
    badges: ['Kilometer King', 'Beach Pup'],
    energyLevel: 'high',
    dogSocialPref: 'loves',
    humanSocialPref: 'loves',
    isNeutered: true,
    isMicrochipped: true,
    vaccinated: true,
    moodStatus: 'playful',
    moodUpdatedAt: d(-1),
    isActive: true,
    createdAt: d(-55),
    updatedAt: NOW,
  },
];

// ── Adoption Dogs ─────────────────────────────────────────────────────────────

export const MOCK_ADOPTION_DOGS: AdoptionDog[] = [
  {
    id: 'adopt_rex',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Rex',
    breed: 'German Shepherd Mix',
    gender: 'male',
    ageMonths: 24,
    weightKg: 30,
    photoURLs: [dogImg('german shepherd', 100), dogImg('german shepherd', 101)],
    bio: 'Rex was found wandering Battersea. He\'s come a long way and is now looking for a forever home with a garden.',
    traits: ['Loyal', 'Smart Cookie', 'Gentle Soul'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'available',
    applicationCount: 3,
    createdAt: d(-30),
  },
  {
    id: 'adopt_pixie',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Pixie',
    breed: 'Chihuahua Mix',
    gender: 'female',
    ageMonths: 14,
    weightKg: 3,
    photoURLs: [dogImg('chihuahua', 110), dogImg('chihuahua', 111)],
    bio: 'Pixie is small but mighty. She loves cuddles, hates rain, and will steal your heart in under 60 seconds.',
    traits: ['Sassy', 'Cuddly', 'Bold'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'available',
    applicationCount: 7,
    createdAt: d(-14),
  },
  {
    id: 'adopt_honey',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Honey',
    breed: 'Labrador Mix',
    gender: 'female',
    ageMonths: 6,
    weightKg: 12,
    photoURLs: [dogImg('labrador puppy', 120), dogImg('labrador puppy', 121), dogImg('labrador puppy', 122)],
    bio: 'Honey is a puppy with boundless love to give. She\'s in foster care and doing brilliantly with children.',
    traits: ['Playful', 'Affectionate', 'Foodie'],
    isNeutered: false,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'available',
    applicationCount: 12,
    createdAt: d(-7),
  },
  {
    id: 'adopt_shadow',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Shadow',
    breed: 'Greyhound',
    gender: 'male',
    ageMonths: 48,
    weightKg: 28,
    photoURLs: [dogImg('greyhound', 130)],
    bio: 'Retired racing greyhound looking for a quiet sofa and kind humans. Counter-surfer but we\'re working on it.',
    traits: ['Gentle Soul', 'Calm', 'Loyal'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'available',
    applicationCount: 2,
    createdAt: d(-21),
  },
  {
    id: 'adopt_bruno',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Bruno',
    breed: 'Rottweiler',
    gender: 'male',
    ageMonths: 36,
    weightKg: 40,
    photoURLs: [dogImg('rottweiler', 140), dogImg('rottweiler', 141)],
    bio: 'Bruno is a big softie who needs an experienced owner. He gives the best leaning cuddles in the business.',
    traits: ['Loyal', 'Bold', 'Protective'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'pending',
    applicationCount: 1,
    createdAt: d(-45),
  },
  {
    id: 'adopt_cleo',
    shelterUid: 'user_shelter',
    shelterName: 'Happy Paws Rescue',
    name: 'Cleo',
    breed: 'Cocker Spaniel Mix',
    gender: 'female',
    ageMonths: 18,
    weightKg: 12,
    photoURLs: [dogImg('cocker spaniel', 150), dogImg('cocker spaniel', 151)],
    bio: 'Cleo was recently adopted into her forever home! She loves long walks in Greenwich Park.',
    traits: ['Affectionate', 'Gentle Soul', 'Adventure Seeker'],
    isNeutered: true,
    isVaccinated: true,
    isMicrochipped: true,
    status: 'adopted',
    applicationCount: 5,
    createdAt: d(-60),
  },
];

// ── Businesses ────────────────────────────────────────────────────────────────

const STANDARD_HOURS = {
  monday: { open: '09:00', close: '18:00' },
  tuesday: { open: '09:00', close: '18:00' },
  wednesday: { open: '09:00', close: '18:00' },
  thursday: { open: '09:00', close: '18:00' },
  friday: { open: '09:00', close: '18:00' },
  saturday: { open: '10:00', close: '16:00' },
  sunday: null,
};

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'biz_vet_hampstead',
    name: 'Hampstead Paws Veterinary',
    category: 'vet',
    description: 'Award-winning vet practice in the heart of Hampstead. Specialists in small animals, with on-site diagnostics and 24/7 emergency cover.',
    address: '42 Heath Street, Hampstead, London NW3 1EN',
    latitude: 51.5570,
    longitude: -0.1780,
    phone: '+44 20 7435 1100',
    website: 'https://example.com/hampstead-paws-vet',
    photoURLs: [img('vet1_photo1'), img('vet1_photo2')],
    rating: 4.8,
    reviewCount: 234,
    openingHours: { ...STANDARD_HOURS, saturday: { open: '09:00', close: '17:00' }, sunday: { open: '10:00', close: '14:00' } },
    isPremiumPartner: true,
    createdAt: d(-365),
  },
  {
    id: 'biz_groomer_camden',
    name: 'Fluffy & Fresh Grooming',
    category: 'groomer',
    description: 'Boutique dog grooming salon specialising in breed-specific cuts, luxury spa treatments, and anxiety-free grooming for nervous dogs.',
    address: '15 Camden High Street, London NW1 7JE',
    latitude: 51.5390,
    longitude: -0.1426,
    phone: '+44 20 7267 8844',
    website: null,
    photoURLs: [img('groomer1_photo1'), img('groomer1_photo2')],
    rating: 4.6,
    reviewCount: 156,
    openingHours: STANDARD_HOURS,
    isPremiumPartner: false,
    createdAt: d(-200),
  },
  {
    id: 'biz_cafe_shoreditch',
    name: 'The Barkery Dog Café',
    category: 'dog_cafe',
    description: 'London\'s cosiest dog-friendly café. Bring your pup, sip craft coffee, and enjoy dog-safe treats alongside your own. No booking needed for small groups.',
    address: '8 Brick Lane, Shoreditch, London E1 6RF',
    latitude: 51.5220,
    longitude: -0.0720,
    phone: '+44 20 7247 5566',
    website: 'https://example.com/the-barkery',
    photoURLs: [img('cafe1_photo1'), img('cafe1_photo2'), img('cafe1_photo3')],
    rating: 4.9,
    reviewCount: 412,
    openingHours: {
      monday: { open: '08:00', close: '17:00' },
      tuesday: { open: '08:00', close: '17:00' },
      wednesday: { open: '08:00', close: '17:00' },
      thursday: { open: '08:00', close: '20:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    isPremiumPartner: true,
    createdAt: d(-300),
  },
  {
    id: 'biz_petstore_notting',
    name: 'Paws Pet Emporium',
    category: 'pet_store',
    description: 'Premium pet supplies, natural food, supplements, and accessories. We stock over 3,000 products including many UK-exclusive brands.',
    address: '33 Portobello Road, Notting Hill, London W11 1LU',
    latitude: 51.5150,
    longitude: -0.2010,
    phone: '+44 20 7229 3300',
    website: 'https://example.com/paws-emporium',
    photoURLs: [img('petstore1_photo1'), img('petstore1_photo2')],
    rating: 4.4,
    reviewCount: 98,
    openingHours: { ...STANDARD_HOURS, saturday: { open: '09:30', close: '18:00' }, sunday: { open: '11:00', close: '17:00' } },
    isPremiumPartner: false,
    createdAt: d(-150),
  },
  {
    id: 'biz_trainer_clapham',
    name: 'London Canine Academy',
    category: 'trainer',
    description: 'Positive-reinforcement training for puppies through to advanced obedience. Group classes, 1:1 sessions, and reactive dog programmes available.',
    address: '7 Clapham Common Southside, London SW4 7AA',
    latitude: 51.4613,
    longitude: -0.1398,
    phone: '+44 20 8673 9900',
    website: 'https://example.com/london-canine-academy',
    photoURLs: [img('trainer1_photo1')],
    rating: 4.7,
    reviewCount: 87,
    openingHours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '08:00', close: '17:00' },
      sunday: { open: '09:00', close: '14:00' },
    },
    isPremiumPartner: true,
    createdAt: d(-180),
  },
  {
    id: 'biz_boarding_battersea',
    name: 'Battersea Boarding Suites',
    category: 'boarding',
    description: 'Five-star dog boarding with individual suites, webcam access for owners, daily walks in Battersea Park, and gourmet meals. Your dog won\'t want to leave.',
    address: '20 Battersea Park Road, London SW11 4LT',
    latitude: 51.4790,
    longitude: -0.1560,
    phone: '+44 20 7622 1188',
    website: 'https://example.com/battersea-boarding',
    photoURLs: [img('boarding1_photo1'), img('boarding1_photo2')],
    rating: 4.5,
    reviewCount: 63,
    openingHours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '20:00' },
      saturday: { open: '07:00', close: '20:00' },
      sunday: { open: '07:00', close: '20:00' },
    },
    isPremiumPartner: false,
    createdAt: d(-250),
  },
];

// ── Events ────────────────────────────────────────────────────────────────────

export const MOCK_EVENTS: DogEvent[] = [
  {
    id: 'event_hampstead_meetup',
    creatorUid: 'user_sarah',
    title: 'Hampstead Heath Dog Meetup 🐕',
    description: 'Monthly off-lead social for all dogs and their humans. We meet at the Kenwood end near the ponds. Bring poo bags, treats, and good vibes!',
    category: 'meetup',
    latitude: 51.5636,
    longitude: -0.1556,
    locationName: 'Hampstead Heath — Kenwood',
    address: 'Kenwood House, Hampstead Lane, London NW3 7JR',
    startAt: d(3, 10, 0),
    endAt: d(3, 12, 0),
    maxAttendees: 50,
    attendeeCount: 23,
    isRSVPd: false,
    coverImageURL: dogImg('dog', 310, 800, 400),
    isPremiumOnly: false,
    createdAt: d(-7),
  },
  {
    id: 'event_puppy_training',
    creatorUid: 'user_olivia',
    title: 'Puppy Foundation Class 🎓',
    description: 'Six-week positive reinforcement programme for puppies 8–16 weeks. Socialisation, sit, stay, recall and lead walking covered. Limit 8 puppies per class.',
    category: 'training',
    latitude: 51.4613,
    longitude: -0.1398,
    locationName: 'London Canine Academy',
    address: '7 Clapham Common Southside, London SW4 7AA',
    startAt: d(5, 11, 0),
    endAt: d(5, 12, 0),
    maxAttendees: 8,
    attendeeCount: 6,
    isRSVPd: false,
    coverImageURL: dogImg('puppy', 311, 800, 400),
    isPremiumOnly: false,
    createdAt: d(-14),
  },
  {
    id: 'event_birthday_bash',
    creatorUid: 'user_sarah',
    title: 'Max\'s 3rd Birthday Bash 🎂🎉',
    description: 'Max is turning 3! Come celebrate with us at the park. There will be a pupcake station, doggy ice cream, and a paddling pool. Humans get prosecco (or tea).',
    category: 'birthday',
    latitude: 51.5604,
    longitude: -0.1620,
    locationName: 'Hampstead Heath — Parliament Hill',
    address: 'Parliament Hill, London NW5 1QR',
    startAt: d(7, 14, 0),
    endAt: d(7, 17, 0),
    maxAttendees: 30,
    attendeeCount: 18,
    isRSVPd: true,
    coverImageURL: dogImg('golden retriever', 312, 800, 400),
    isPremiumOnly: false,
    createdAt: d(-10),
  },
  {
    id: 'event_charity_walk',
    creatorUid: 'user_emma',
    title: 'Charity Walkies for Dogs Trust 🎗️',
    description: 'Join us for a 5km sponsored walk through Hyde Park in aid of Dogs Trust. All dogs welcome. Raise £20+ and your dog gets an official finisher bandana!',
    category: 'charity',
    latitude: 51.5074,
    longitude: -0.1657,
    locationName: 'Hyde Park — Diana Memorial Fountain',
    address: 'Hyde Park, London W2 2UH',
    startAt: d(10, 9, 30),
    endAt: d(10, 13, 0),
    maxAttendees: 200,
    attendeeCount: 87,
    isRSVPd: false,
    coverImageURL: dogImg('dog', 313, 800, 400),
    isPremiumOnly: false,
    createdAt: d(-20),
  },
];

// ── Lost Reports ──────────────────────────────────────────────────────────────

export const MOCK_LOST_REPORTS: LostReport[] = [
  {
    id: 'lost_biscuit',
    reporterUid: 'user_james',
    dogId: null,
    dogName: 'Biscuit',
    dogBreed: 'Jack Russell Terrier',
    dogPhotoURL: dogImg('jack russell terrier', 160),
    dogDescription: 'Tan and white Jack Russell, male, no collar when lost. Responds to "Biscuit". Has a small scar above left eye.',
    status: 'lost',
    lastSeenLatitude: 51.5237,
    lastSeenLongitude: -0.0770,
    lastSeenAddress: 'Shoreditch High Street near Old Street roundabout',
    lastSeenAt: d(-1, 16, 30),
    rewardOffered: true,
    rewardAmount: 250,
    contactPhone: '+44 7700 900123',
    sightings: [
      {
        id: 'sighting_1',
        reportId: 'lost_biscuit',
        reporterUid: 'user_liam',
        latitude: 51.5240,
        longitude: -0.0780,
        address: 'Curtain Road, Shoreditch',
        note: 'Saw him running east on Curtain Road, looked scared but uninjured.',
        photoURL: null,
        seenAt: d(-1, 18, 15),
        createdAt: d(-1, 18, 20),
      },
    ],
    isBroadcast: true,
    createdAt: d(-1, 16, 45),
    updatedAt: d(-1, 18, 25),
  },
  {
    id: 'lost_cookie',
    reporterUid: 'user_olivia',
    dogId: null,
    dogName: 'Cookie',
    dogBreed: 'Maltese',
    dogPhotoURL: dogImg('maltese', 170),
    dogDescription: 'White Maltese, female, 3 years old. Wearing a pink collar with a bone-shaped tag. Very friendly.',
    status: 'sighted',
    lastSeenLatitude: 51.4613,
    lastSeenLongitude: -0.1378,
    lastSeenAddress: 'Clapham Common, near the bandstand',
    lastSeenAt: d(-2, 11, 0),
    rewardOffered: false,
    rewardAmount: null,
    contactPhone: '+44 7700 900456',
    sightings: [
      {
        id: 'sighting_2',
        reportId: 'lost_cookie',
        reporterUid: 'user_emma',
        latitude: 51.4620,
        longitude: -0.1390,
        address: 'Clapham High Street',
        note: 'Spotted near the Sainsbury\'s entrance, being coaxed by staff. She ran off towards the park.',
        photoURL: dogImg('maltese', 171),
        seenAt: d(-1, 9, 30),
        createdAt: d(-1, 9, 45),
      },
    ],
    isBroadcast: true,
    createdAt: d(-2, 11, 30),
    updatedAt: d(-1, 9, 50),
  },
  {
    id: 'lost_zeus',
    reporterUid: 'user_sarah',
    dogId: null,
    dogName: 'Zeus',
    dogBreed: 'Husky',
    dogPhotoURL: dogImg('husky', 180),
    dogDescription: 'Black and white Husky, male, blue eyes. Microchipped. Escaped from garden in Primrose Hill. Very friendly, will approach people.',
    status: 'found',
    lastSeenLatitude: 51.5392,
    lastSeenLongitude: -0.1591,
    lastSeenAddress: 'Fitzroy Road, Primrose Hill',
    lastSeenAt: d(-5, 8, 0),
    rewardOffered: false,
    rewardAmount: null,
    contactPhone: '+44 7700 900789',
    sightings: [],
    isBroadcast: true,
    createdAt: d(-5, 8, 30),
    updatedAt: d(-4, 14, 0),
  },
];

// ── Posts ─────────────────────────────────────────────────────────────────────

export const MOCK_POSTS: Post[] = [
  {
    id: 'post_1',
    authorUid: 'user_sarah',
    authorDogId: 'dog_max',
    type: 'photo',
    text: 'Golden hour at Hampstead Heath never gets old 🌅 Max insisted on posing for at least 47 photos before agreeing one was good enough.',
    mediaURLs: [dogImg('golden retriever', 301, 800, 600)],
    reactions: { woof: 42, heart: 28, paw: 15, laugh: 3, wow: 7 },
    myReaction: null,
    commentCount: 12,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-1, 18, 30),
    updatedAt: d(-1, 18, 30),
  },
  {
    id: 'post_2',
    authorUid: 'user_james',
    authorDogId: 'dog_luna',
    type: 'photo',
    text: 'Luna discovered the mud pit at Primrose Hill. She is UNREPENTANT. Bath time is going to be a battle. 💀',
    mediaURLs: [dogImg('border collie', 302, 800, 600), dogImg('border collie', 303, 800, 600)],
    reactions: { woof: 18, heart: 9, paw: 6, laugh: 34, wow: 2 },
    myReaction: null,
    commentCount: 8,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-1, 14, 15),
    updatedAt: d(-1, 14, 15),
  },
  {
    id: 'post_3',
    authorUid: 'user_emma',
    authorDogId: 'dog_cooper',
    type: 'photo',
    text: 'Cooper got his first agility rosette today!! He knocked over 4 jumps, ran through the tunnel backwards, and stole a treat from the judge\'s pocket — but he got there eventually 🏆',
    mediaURLs: [dogImg('labrador retriever', 304, 800, 600)],
    reactions: { woof: 65, heart: 43, paw: 29, laugh: 21, wow: 14 },
    myReaction: null,
    commentCount: 22,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-2, 16, 0),
    updatedAt: d(-2, 16, 0),
  },
  {
    id: 'post_4',
    authorUid: 'user_liam',
    authorDogId: 'dog_bella',
    type: 'text',
    text: 'Bella has developed a new hobby: judging everyone at the dog park from a safe distance without participating. She sat on the bench with me for 45 minutes, watched other dogs play, then demanded we go home. She\'s me. I am Bella.',
    mediaURLs: [],
    reactions: { woof: 31, heart: 44, paw: 12, laugh: 89, wow: 5 },
    myReaction: null,
    commentCount: 33,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-2, 20, 30),
    updatedAt: d(-2, 20, 30),
  },
  {
    id: 'post_5',
    authorUid: 'user_olivia',
    authorDogId: 'dog_charlie',
    type: 'event',
    text: '🎉 We\'re hosting a birthday bash for Max on Saturday! Charlie and I will be there with homemade pupcakes. Come celebrate with us at Parliament Hill! 🎂',
    mediaURLs: [dogImg('cockapoo', 305, 800, 600)],
    reactions: { woof: 24, heart: 31, paw: 18, laugh: 4, wow: 9 },
    myReaction: null,
    commentCount: 15,
    eventRef: 'event_birthday_bash',
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-3, 10, 0),
    updatedAt: d(-3, 10, 0),
  },
  {
    id: 'post_6',
    authorUid: 'user_emma',
    authorDogId: 'dog_buddy',
    type: 'lost_alert',
    text: '🚨 LOST DOG — Biscuit the Jack Russell was last seen near Old Street yesterday evening. Please share widely! Contact details in the report.',
    mediaURLs: [dogImg('jack russell terrier', 160)],
    reactions: { woof: 5, heart: 3, paw: 2, laugh: 0, wow: 1 },
    myReaction: null,
    commentCount: 4,
    eventRef: null,
    lostReportRef: 'lost_biscuit',
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-1, 19, 0),
    updatedAt: d(-1, 19, 0),
  },
  {
    id: 'post_7',
    authorUid: 'user_shelter',
    authorDogId: 'dog_max',
    type: 'adoption',
    text: '🐶 Meet Honey! This 6-month-old Labrador mix is looking for her forever home. She\'s brilliant with children and other dogs. Applications open now — link in profile.',
    mediaURLs: [dogImg('labrador puppy', 120), dogImg('labrador puppy', 121)],
    reactions: { woof: 78, heart: 102, paw: 55, laugh: 2, wow: 23 },
    myReaction: null,
    commentCount: 41,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: 'adopt_honey',
    isPublic: true,
    createdAt: d(-3, 12, 0),
    updatedAt: d(-3, 12, 0),
  },
  {
    id: 'post_8',
    authorUid: 'user_sarah',
    authorDogId: 'dog_rosie',
    type: 'tip',
    text: '💡 Dog care tip: Did you know Cavaliers are prone to overheating in summer? We keep Rosie\'s walks to early morning and evening during hot spells, and always carry a collapsible water bowl. Sharing in case it helps other spaniel owners! 🌡️',
    mediaURLs: [],
    reactions: { woof: 15, heart: 28, paw: 9, laugh: 1, wow: 6 },
    myReaction: null,
    commentCount: 7,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-4, 9, 0),
    updatedAt: d(-4, 9, 0),
  },
  {
    id: 'post_9',
    authorUid: 'user_james',
    authorDogId: 'dog_daisy',
    type: 'photo',
    text: 'Daisy decided that a squirrel was more important than our recall training session. We\'re going back to basics. Again. 🐿️',
    mediaURLs: [dogImg('dachshund', 306, 800, 600)],
    reactions: { woof: 27, heart: 19, paw: 8, laugh: 56, wow: 3 },
    myReaction: null,
    commentCount: 14,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-5, 11, 30),
    updatedAt: d(-5, 11, 30),
  },
  {
    id: 'post_10',
    authorUid: 'user_olivia',
    authorDogId: 'dog_mia',
    type: 'photo',
    text: 'Mia graduated from her puppy class today! She only bit the instructor once and it was very gentle. We\'re calling it a success 🎓✨',
    mediaURLs: [dogImg('toy poodle', 307, 800, 600), dogImg('toy poodle', 308, 800, 600)],
    reactions: { woof: 49, heart: 62, paw: 33, laugh: 17, wow: 11 },
    myReaction: null,
    commentCount: 28,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-5, 17, 0),
    updatedAt: d(-5, 17, 0),
  },
  {
    id: 'post_11',
    authorUid: 'user_emma',
    authorDogId: 'dog_cooper',
    type: 'event',
    text: '🎗️ We\'re joining the Dogs Trust charity walk next weekend! Cooper and Buddy are training hard (read: eating extra treats for fuel). Come walk with us and raise money for a brilliant cause!',
    mediaURLs: [dogImg('labrador retriever', 309, 800, 600)],
    reactions: { woof: 33, heart: 41, paw: 22, laugh: 5, wow: 8 },
    myReaction: null,
    commentCount: 16,
    eventRef: 'event_charity_walk',
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-6, 13, 0),
    updatedAt: d(-6, 13, 0),
  },
  {
    id: 'post_12',
    authorUid: 'user_liam',
    authorDogId: 'dog_bear',
    type: 'tip',
    text: '🐻 PSA from a Bernese Mountain Dog owner: these gentle giants need more exercise than their chill demeanour suggests. Bear does 1.5 hours a day and is a completely different dog (in a good way) compared to when we did 30 minutes. Please do your breed research before adopting!',
    mediaURLs: [],
    reactions: { woof: 88, heart: 112, paw: 67, laugh: 3, wow: 29 },
    myReaction: null,
    commentCount: 45,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-7, 21, 0),
    updatedAt: d(-7, 21, 0),
  },
  {
    id: 'post_13',
    authorUid: 'user_noah',
    authorDogId: 'dog_atlas',
    type: 'photo',
    text: 'Atlas and Finn absolutely demolished a 12km trail through Richmond Park this morning. One has the energy of a puppy. The other is a puppy. I am neither. Send help. 🏃',
    mediaURLs: [dogImg('australian shepherd', 314, 800, 600), dogImg('irish setter', 315, 800, 600)],
    reactions: { woof: 36, heart: 22, paw: 14, laugh: 11, wow: 5 },
    myReaction: null,
    commentCount: 9,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(0, 8, 45),
    updatedAt: d(0, 8, 45),
  },
  {
    id: 'post_14',
    authorUid: 'user_ava',
    authorDogId: 'dog_pepper',
    type: 'photo',
    text: 'Pepper just had her summer groom and she is AWARE of how good she looks. Strutting around Richmond Green like she owns it. 💅',
    mediaURLs: [dogImg('miniature schnauzer', 316, 800, 600)],
    reactions: { woof: 53, heart: 71, paw: 38, laugh: 8, wow: 16 },
    myReaction: null,
    commentCount: 19,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-1, 13, 0),
    updatedAt: d(-1, 13, 0),
  },
  {
    id: 'post_15',
    authorUid: 'user_marcus',
    authorDogId: 'dog_rex',
    type: 'text',
    text: 'Reminder that Staffordshire Bull Terriers are consistently ranked one of the most affectionate, people-loving breeds. Rex cried for 20 minutes when the neighbours\' kid went home. He is a menace only to your dry eyes. Breed bias is real — do your research before judging a dog by its looks. 🐾❤️',
    mediaURLs: [],
    reactions: { woof: 142, heart: 198, paw: 87, laugh: 6, wow: 41 },
    myReaction: null,
    commentCount: 67,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-2, 19, 30),
    updatedAt: d(-2, 19, 30),
  },
  {
    id: 'post_16',
    authorUid: 'user_priya',
    authorDogId: 'dog_nala',
    type: 'photo',
    text: 'Nala\'s first trip to The Barkery in Shoreditch and she immediately made friends with every single person in there. The barista gave her a puppuccino and she accepted it like a queen receiving tribute. 👑☕',
    mediaURLs: [dogImg('shih tzu', 317, 800, 600), dogImg('shih tzu', 318, 800, 600)],
    reactions: { woof: 61, heart: 84, paw: 47, laugh: 12, wow: 19 },
    myReaction: null,
    commentCount: 24,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-3, 15, 30),
    updatedAt: d(-3, 15, 30),
  },
  {
    id: 'post_17',
    authorUid: 'user_noah',
    authorDogId: 'dog_finn',
    type: 'photo',
    text: 'Finn\'s recall is still a work in progress but nobody told him that red setters are supposed to be trainable. He is fluent only in "run" and "zoomies". 10/10 would not change a thing. 🧡',
    mediaURLs: [dogImg('irish setter', 319, 800, 600)],
    reactions: { woof: 44, heart: 58, paw: 31, laugh: 37, wow: 7 },
    myReaction: null,
    commentCount: 18,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-4, 17, 0),
    updatedAt: d(-4, 17, 0),
  },
  {
    id: 'post_18',
    authorUid: 'user_ava',
    authorDogId: 'dog_pepper',
    type: 'tip',
    text: '💡 Schnauzer owners: strip, don\'t clip! If you want to maintain that classic wiry coat, hand-stripping twice a year is the way to go. Clipping gives a softer, lighter result. Ask your groomer which they offer — it makes a huge difference long term. Pepper is a strip-only girl and her coat has never been better.',
    mediaURLs: [],
    reactions: { woof: 29, heart: 41, paw: 18, laugh: 0, wow: 12 },
    myReaction: null,
    commentCount: 11,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-5, 10, 0),
    updatedAt: d(-5, 10, 0),
  },
  {
    id: 'post_19',
    authorUid: 'user_marcus',
    authorDogId: 'dog_rex',
    type: 'photo',
    text: 'Rex met Atlas at Greenwich Park today and they are now best friends. Two extremely extra dogs doing extremely extra zoomies for 45 minutes straight. Greenwich has never seen anything like it. 🐾🌪️',
    mediaURLs: [dogImg('staffordshire bull terrier', 320, 800, 600)],
    reactions: { woof: 77, heart: 93, paw: 52, laugh: 28, wow: 14 },
    myReaction: null,
    commentCount: 32,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-6, 16, 15),
    updatedAt: d(-6, 16, 15),
  },
  {
    id: 'post_20',
    authorUid: 'user_priya',
    authorDogId: 'dog_nala',
    type: 'photo',
    text: 'Tried doga (dog yoga) with Nala this morning in Bishops Park. She did savasana for 45 minutes. Zero effort, maximum serenity. She is naturally enlightened. Namaste. 🧘🐾',
    mediaURLs: [dogImg('shih tzu', 321, 800, 600)],
    reactions: { woof: 58, heart: 76, paw: 43, laugh: 34, wow: 21 },
    myReaction: null,
    commentCount: 26,
    eventRef: null,
    lostReportRef: null,
    adoptionDogRef: null,
    isPublic: true,
    createdAt: d(-8, 9, 30),
    updatedAt: d(-8, 9, 30),
  },
];

export const MOCK_FEED_PAGE: FeedPage = {
  items: MOCK_POSTS,
  cursor: null,
  hasMore: false,
};

// ── Match Results ─────────────────────────────────────────────────────────────

/** Mock matches for any active dog. Target dogs are all MOCK_DOGS. */
export const MOCK_MATCHES: MatchResult[] = [
  {
    dog: MOCK_DOGS[1], // Luna
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_luna',
      score: 92,
      breakdown: { traits: 90, energy: 95, size: 85, social: 95, distance: 95 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[4], // Charlie
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_charlie',
      score: 87,
      breakdown: { traits: 88, energy: 90, size: 82, social: 92, distance: 80 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[2], // Cooper
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_cooper',
      score: 84,
      breakdown: { traits: 80, energy: 80, size: 90, social: 92, distance: 85 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[7], // Buddy
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_buddy',
      score: 79,
      breakdown: { traits: 75, energy: 75, size: 88, social: 90, distance: 72 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[8], // Mia
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_mia',
      score: 74,
      breakdown: { traits: 78, energy: 70, size: 65, social: 88, distance: 78 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[5], // Daisy
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_daisy',
      score: 69,
      breakdown: { traits: 65, energy: 60, size: 72, social: 80, distance: 90 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[6], // Rosie
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_rosie',
      score: 66,
      breakdown: { traits: 70, energy: 55, size: 68, social: 85, distance: 60 },
      computedAt: d(-1),
    },
  },
  {
    dog: MOCK_DOGS[9], // Bear
    match: {
      dogId: 'dog_active',
      targetDogId: 'dog_bear',
      score: 58,
      breakdown: { traits: 60, energy: 45, size: 50, social: 82, distance: 65 },
      computedAt: d(-1),
    },
  },
];

// ── Map Pins ──────────────────────────────────────────────────────────────────

export const MOCK_MAP_PINS: MapPin[] = [
  // Businesses
  { type: 'business', businessId: 'biz_vet_hampstead', name: 'Hampstead Paws Vet', category: 'vet', latitude: 51.5570, longitude: -0.1780, rating: 4.8 },
  { type: 'business', businessId: 'biz_groomer_camden', name: 'Fluffy & Fresh Grooming', category: 'groomer', latitude: 51.5390, longitude: -0.1426, rating: 4.6 },
  { type: 'business', businessId: 'biz_cafe_shoreditch', name: 'The Barkery Dog Café', category: 'dog_cafe', latitude: 51.5220, longitude: -0.0720, rating: 4.9 },
  { type: 'business', businessId: 'biz_petstore_notting', name: 'Paws Pet Emporium', category: 'pet_store', latitude: 51.5150, longitude: -0.2010, rating: 4.4 },
  { type: 'business', businessId: 'biz_trainer_clapham', name: 'London Canine Academy', category: 'trainer', latitude: 51.4613, longitude: -0.1398, rating: 4.7 },
  { type: 'business', businessId: 'biz_boarding_battersea', name: 'Battersea Boarding Suites', category: 'boarding', latitude: 51.4790, longitude: -0.1560, rating: 4.5 },
  // Lost dogs
  { type: 'lost', reportId: 'lost_biscuit', dogName: 'Biscuit', photoURL: dogImg('jack russell terrier', 160), latitude: 51.5237, longitude: -0.0770, lastSeenAt: d(-1, 16, 30) },
  { type: 'lost', reportId: 'lost_cookie', dogName: 'Cookie', photoURL: dogImg('maltese', 170), latitude: 51.4613, longitude: -0.1378, lastSeenAt: d(-2, 11, 0) },
];

// ── Calendar Entries ──────────────────────────────────────────────────────────

export const MOCK_CALENDAR_ENTRIES: CalendarEntry[] = [
  {
    id: 'cal_vet',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: null,
    title: 'Max — Annual Vet Check',
    notes: 'Booster vaccines due. Bring vaccination record.',
    startAt: d(1, 10, 0),
    endAt: d(1, 10, 45),
    category: 'vet',
    reminderMinutes: 60,
    createdAt: d(-7),
  },
  {
    id: 'cal_playdate',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: null,
    title: 'Playdate with Luna & Daisy',
    notes: 'Meeting at Regent\'s Park off-lead area. Bring the long lead for recall practice.',
    startAt: d(2, 9, 30),
    endAt: d(2, 11, 30),
    category: 'playdate',
    reminderMinutes: 30,
    createdAt: d(-3),
  },
  {
    id: 'cal_training',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: null,
    title: 'Group Training Class',
    notes: 'Advanced recall & distraction work. Remember to bring high-value treats (cheese or chicken).',
    startAt: d(3, 18, 30),
    endAt: d(3, 19, 30),
    category: 'training',
    reminderMinutes: 60,
    createdAt: d(-5),
  },
  {
    id: 'cal_grooming',
    ownerUid: 'user_sarah',
    dogId: 'dog_rosie',
    eventId: null,
    title: 'Rosie — Grooming Appointment',
    notes: 'Full groom + ear cleaning at Fluffy & Fresh. Drop off 10am, collect 1pm.',
    startAt: d(4, 10, 0),
    endAt: d(4, 13, 0),
    category: 'grooming',
    reminderMinutes: 60,
    createdAt: d(-10),
  },
  {
    id: 'cal_birthday',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: 'event_birthday_bash',
    title: 'Max\'s 3rd Birthday Party 🎂',
    notes: 'Parliament Hill. Order pupcakes from The Barkery. Bring spare towels and the paddling pool.',
    startAt: d(7, 14, 0),
    endAt: d(7, 17, 0),
    category: 'birthday',
    reminderMinutes: 120,
    createdAt: d(-10),
  },
  {
    id: 'cal_charity',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: 'event_charity_walk',
    title: 'Dogs Trust Charity Walk 🎗️',
    notes: 'Hyde Park, Diana Memorial. Meet Cooper & Buddy at the gate.',
    startAt: d(10, 9, 30),
    endAt: d(10, 13, 0),
    category: 'charity',
    reminderMinutes: 90,
    createdAt: d(-5),
  },
  {
    id: 'cal_medication',
    ownerUid: 'user_sarah',
    dogId: 'dog_rosie',
    eventId: null,
    title: 'Rosie — Flea & Worm Treatment',
    notes: 'Monthly Advocate spot-on. Wear gloves!',
    startAt: d(14, 8, 0),
    endAt: d(14, 8, 15),
    category: 'medication',
    reminderMinutes: 1440,
    createdAt: d(-2),
  },
  {
    id: 'cal_meetup',
    ownerUid: 'user_sarah',
    dogId: 'dog_max',
    eventId: 'event_hampstead_meetup',
    title: 'Hampstead Heath Monthly Meetup',
    notes: 'Kenwood end. Arrive early to grab a good spot.',
    startAt: d(3, 10, 0),
    endAt: d(3, 12, 0),
    category: 'meetup',
    reminderMinutes: 60,
    createdAt: d(-1),
  },
];
